### ISSUE TITLE
Ask for distance matrix data for the "constructed data"

### ISSUE THREAD

**Issue by tz05** [ShanKothari/DecomposingFD#7] opened 2018-04-13 23:26 UTC
Hi Shan,

I am reading this paper. Your code would be very helpful. I try to figure out how the metrics were calculated for the "constructed data" (Fig. 2 and Table 1) using your code. For many metrics, my results are not consistent with what were reported in Table 1. My guess is that the distance matrix I made based on Fig. 2 was not same as yours due to standardization or other data pre-processing. Could you please upload the distance matrix or just send me a copy privately through Email? That way I could better understand these metrics and apply your code in my research. I had a hard time to digest the claim that evenly-distributed species on the outer boundary of the trait space would result in a M.prime of 1. I believe your distance matrix for the "constructed data" would be greatly helpful. Thanks a lot in advance! You could send the matrix to tz05@me.com if you prefer to using Email.

Sincerely,

Tao

**Comment by ShanKothari** [comment] 2018-04-16 22:15
Hello Tao,

I don't actually have the functional "trait" matrices from the constructed landscapes in Fig. 2, and I didn't use those to validate that my code works. (Instead, I checked that Evsey Kosman and I got the same results on a dataset I sent him.) If you have those trait data from another source, I could perhaps check what it going on. Please feel free to email me at kotha020 [at] umn [dot] edu; I will close this issue on GitHub unless I can confirm that there is an issue with how my code implements the paper's calculations.

The claim about the dispersion M' is that if all your species pairs are as far apart from each other as the maximally distant species pair (i.e. all species are equally distant from all other species), M' will be 1 by definition. This is because d_ij=1 for all i!=j.

Sincerely,
Shan

**Closed as completed** 2018-04-16 22:16 UTC
